### ISSUE TITLE
Doesn't work in Windows

### ISSUE THREAD

**Issue by nagaozen** [obeattie/smooshy-py#1]
This extension doesn't work in Windows because it seems to require fcntl module.

```
Traceback (most recent call last):
  File "C:\Python26\Scripts\smooshy-script.py", line 8, in <module>
    load_entry_point('Smooshy==0.1', 'console_scripts', 'smooshy')()
  File "C:\Python26\lib\site-packages\pkg_resources.py", line 277, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Python26\lib\site-packages\pkg_resources.py", line 2180, in load_entry_point
    return ep.load()
  File "C:\Python26\lib\site-packages\pkg_resources.py", line 1913, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "build\bdist.win32\egg\smooshy\smoosher.py", line 2, in <module>
ImportError: No module named fcntl
```

**Comment by obeattie** [comment]
I don't have a Windows machine so I have no way to test what would work. If you'd like to fix it, feel free to fork and I'll gladly pull your changes =)
